# Generated by Django 4.2.14 on 2024-07-30 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100, verbose_name='Nombre')),
                ('rut_empresa', models.CharField(max_length=100, verbose_name='Rut')),
                ('direccion_empresa', models.CharField(max_length=100, verbose_name='Direccion')),
                ('telefono_empresa', models.CharField(max_length=30, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Empresas',
                'ordering': ['rut_empresa'],
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_empleado', models.CharField(max_length=100, verbose_name='Apellido')),
                ('rut_empleado', models.CharField(max_length=30, verbose_name='Rut')),
                ('email', models.EmailField(max_length=254)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpli.empresas', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': ['Empleados'],
                'ordering': ['rut_empleado'],
            },
        ),
    ]
