# Generated by Django 4.2.14 on 2024-07-30 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpli', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleados',
            options={'ordering': ['rut_empleado'], 'verbose_name': 'Empleados'},
        ),
    ]
